[package]
name = "price-discovery"
version = "0.0.0"
authors = ["Dorin Iancu <dorin.iancu@elrond.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies]
hex-literal = "0.3.1"

[dependencies.multiversx-sc]
version = "=0.45.2"
features = ["esdt-token-payment-legacy-decode"]

[dependencies.multiversx-sc-modules]
version = "=0.45.2"

[dependencies.locking_module]
path = "../../common/modules/locking_module"

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"

[dev-dependencies.simple-lock]
path = "../../locked-asset/simple-lock"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.45.2"
