[package]
name = "whitelist_module"
version = "0.0.0"
authors = [ "you" ]
edition = "2018"

[lib]
path = "src/whitelist_module.rs"

[dependencies.common_errors]
path = "../../common_errors"

[dependencies.elrond-wasm]
version = "0.34.0"
