[workspace]
members = [
  "dex",
  "dex/farm",
  "dex/farm/meta",
  "dex/farm/interact-rs",
  "dex/pair",
  "dex/pair/meta",
  "dex/router",
  "dex/router/meta",
  "dex/fuzz",
  "dex/governance",
  "dex/governance/meta",
  "dex/price-discovery",
  "dex/price-discovery/meta",
  "dex/proxy-deployer",
  "dex/proxy-deployer/meta",
  "dex/pair-mock",
  "dex/pair-mock/meta",

  "energy-integration/energy-factory-mock",
  "energy-integration/energy-factory-mock/meta",
  "energy-integration/fees-collector",
  "energy-integration/fees-collector/meta",
  "energy-integration/governance-v2",
  "energy-integration/governance-v2/meta",

  "farm-staking/farm-staking",
  "farm-staking/farm-staking/meta",
  "farm-staking/farm-staking-proxy",
  "farm-staking/farm-staking-proxy/meta",
  "farm-staking/metabonding-staking",
  "farm-staking/metabonding-staking/meta",

  "locked-asset/",
  "locked-asset/distribution",
  "locked-asset/distribution/meta",
  "locked-asset/proxy_dex",
  "locked-asset/proxy_dex/meta",
  "locked-asset/factory",
  "locked-asset/factory/meta",
  "locked-asset/simple-lock",
  "locked-asset/simple-lock/meta",

  "pause-all",
  "pause-all/meta",
]
