[package]
name = "lkmex-transfer-abi"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false
[dependencies.lkmex-transfer]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.2"
