[package]
name = "farm-with-locked-rewards-meta"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false
[dependencies.farm-with-locked-rewards]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.2"
