[package]
name = "common-events"
version = "0.0.0"
authors = [ "you" ]
edition = "2018"

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.34.0"

[dependencies.common-types]
path = "../../common-types"

[dependencies.simple-lock-energy]
path = "../../../locked-asset/simple-lock-energy"