[package]
name = "farm-staking-proxy-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["you"]

[dev-dependencies]
[dependencies.farm-staking-proxy]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.2"
