[package]
name = "token_unstake"
version = "0.0.0"
authors = [ "Sorin Petreasca <sorin.petreasca@elrond.com>" ]
edition = "2018"

[lib]
path = "src/token_unstake.rs"

[dependencies.common_structs]
path = "../../common_structs"

[dependencies.common_errors]
path = "../../common_errors"

[dependencies.token_send]
path = "../token_send"

[dependencies.elrond-wasm]
version = "=0.36.1"
features = ["esdt-token-payment-legacy-decode",]