[package]
name = "simple-lock-whitelist-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Dorin Iancu <dorin.iancu@multiversx.com>"]

[dependencies.simple-lock-whitelist]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.49.0-alpha.3"
default-features = false
