[package]
name = "simple-lock-whitelist-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Dorin Iancu <dorin.iancu@elrond.com>"]
[dependencies.simple-lock-whitelist]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.2"
