[package]
name = "fees-collector"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "0.36.0"
features = ["esdt-token-payment-legacy-decode",]

[dependencies.elrond-wasm-modules]
version = "0.36.0"

[dependencies.energy-query]
path = "../common-modules/energy-query"

[dependencies.week-timekeeping]
path = "../common-modules/week-timekeeping"

[dependencies.weekly-rewards-splitting]
path = "../common-modules/weekly-rewards-splitting"

[dependencies.common-types]
path = "../common-types"

[dev-dependencies.elrond-wasm-debug]
version = "0.36.0"

[dev-dependencies]
num-bigint = "0.4.2"

[dev-dependencies.energy-factory-mock]
path = "../energy-factory-mock"
