[package]
name = "sc-dex-helper-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.sc-dex-helper]
path = ".."

[dependencies.elrond-wasm]
version = "0.17"

[dependencies.elrond-wasm-debug]
version = "0.17"

