[package]
name = "events"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@multiversx.com>" ]
edition = "2018"

[lib]
path = "src/events.rs"

[dependencies.common_structs]
path = "../../../common_structs"

[dependencies.contexts]
path = "../contexts"

[dependencies.elrond-wasm]
version = "=0.36.1"
features = ["esdt-token-payment-legacy-decode",]
