[package]
name = "token-unstake-abi"
version = "0.0.0"
authors = ["you"]
edition = "2021"
publish = false
[dependencies.token-unstake]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.4"
