[package]
name = "distribution-abi"
version = "0.0.0"
authors = ["MultiversX <contact@multiversx.com>"]
edition = "2021"
publish = false

[dependencies.distribution]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.49.0-alpha.4"
default-features = false
