[package]
name = "simple-lock-energy"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.simple-lock]
path = "../simple-lock"

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.elrond-wasm]
version = "0.34.1"

[dependencies.elrond-wasm-modules]
version = "0.34.1"

[dev-dependencies.elrond-wasm-debug]
version = "0.34.1"

[dev-dependencies]
num-bigint = "0.4.2"
num-traits = "0.2"
hex = "0.4"
