[package]
name = "farm-staking-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.farm-staking]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.48.1"
default-features = false