[package]
name = "proxy_dex"
version = "0.0.0"
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.itertools]
version = "0.10.1"
default-features = false

[dependencies.pair]
path = "../../dex/pair"

[dependencies.farm]
path = "../../dex/farm"

[dependencies.token_merge_helper]
path = "../../common/modules/token_merge_helper"

[dependencies.token_send]
path = "../../common/modules/token_send"

[dependencies.utils]
path = "../../common/modules/utils"

[dependencies.elrond-wasm]
version = "0.36.0"
features = ["esdt-token-payment-legacy-decode",]

[dependencies.elrond-wasm-modules]
version = "0.36.0"

[dev-dependencies.elrond-wasm-debug]
version = "0.36.0"
