[package]
name = "proxy_dex"
version = "0.0.0"
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.common_structs]
path = "../../common/common_structs"

[dependencies.token_merge]
path = "../../common/modules/token_merge"

[dependencies.token_send]
path = "../../common/modules/token_send"

[dependencies.elrond-wasm]
version = "=0.36.1"
features = [ "esdt-token-payment-legacy-decode" ]

[dev-dependencies.elrond-wasm-debug]
version = "=0.36.1"
