[package]
name = "farm_with_community_rewards-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.farm_with_community_rewards]
path = ".."

[dependencies.elrond-wasm]
version = "0.34.1"

[dependencies.elrond-wasm-debug]
version = "0.34.1"
