[package]
name = "proxy_dex-meta"

version = "0.0.0"
authors = [ "you",]
edition = "2021"
publish = false

[dependencies.proxy_dex]
path = ".."

[dependencies.elrond-wasm]
version = "=0.37.0"

[dependencies.elrond-wasm-debug]
version = "=0.37.0"
