[package]
name = "proxy_dex-meta"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.proxy_dex]
path = ".."

[dependencies.elrond-wasm]
version = "=0.36.1"
features = [ "esdt-token-payment-legacy-decode" ]

[dependencies.elrond-wasm-debug]
version = "=0.36.1"
