[package]
name = "farm_position"
version = "0.0.0"
authors = ["MultiversX <contact@multiversx.com>"]
edition = "2021"

[lib]
path = "src/farm_position.rs"

[dependencies.multiversx-sc]
version = "=0.39.4"
features = ["esdt-token-payment-legacy-decode"]

[dependencies.multiversx-sc-modules]
version = "=0.39.4"

[dependencies.farm_token]
path = "../farm_token"

[dependencies.utils]
path = "../../utils"

[dependencies.permissions_module]
path = "../../permissions_module"

[dependencies.common_structs]
path = "../../../common_structs"
