[package]
name = "math"
version = "0.0.0"
authors = [ "Dorin Iancu <dorin.iancu@elrond.com>" ]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "=0.38.0"
features = ["esdt-token-payment-legacy-decode",]
