[package]
name = "energy-update"
version = "0.0.0"
authors = [ "you",]
edition = "2021"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.elrond-wasm]
version = "=0.38.0"
features = ["esdt-token-payment-legacy-decode",]

[dependencies.elrond-wasm-modules]
version = "=0.38.0"

[dependencies.farm]
path = "../../dex/farm"

[dependencies.weekly-rewards-splitting]
path = "../common-modules/weekly-rewards-splitting"

[dev-dependencies.elrond-wasm-debug]
version = "=0.38.0"

[dev-dependencies]
num-bigint = "0.4.2"
