[package]
 name = "community_rewards"
 version = "0.0.0"
 authors = [ "Sorin Petreasca <sorin.petreasca@elrond.com>" ]
 edition = "2018"

[lib]
path = "src/community_rewards.rs"

[dependencies.common_structs]
path = "../../../common_structs"

[dependencies.common_errors]
path = "../../../common_errors"

[dependencies.config]
path = "../config"

[dependencies.farm_token]
path = "../farm_token"

[dependencies.token_send]
path = "../../token_send"

[dependencies.pausable]
path = "../../pausable"

[dependencies.elrond-wasm]
version = "0.34.1"

[dependencies.elrond-wasm-modules]
version = "0.34.1"
