[package]
name = "farm-staking"
version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"

[dependencies.config]
path = "../../common/modules/farm/config"

[dependencies.farm_token]
path = "../../common/modules/farm/farm_token"

[dependencies.rewards]
path = "../../common/modules/farm/rewards"

[dependencies.token_send]
path = "../../common/modules/token_send"

[dependencies.token_merge_old]
path = "../../common/modules/token_merge_old"

[dependencies.common_structs_old]
path = "../../common/common_structs_old"

[dependencies.common_errors_old]
path = "../../common/common_errors_old"

[dev-dependencies.multiversx-sc-scenario]
version = "=0.48.1"

[dev-dependencies.multiversx-sc-modules]
version = "=0.48.1"

[dependencies.multiversx-sc]
version = "=0.48.1"
features = ["esdt-token-payment-legacy-decode"]

[dev-dependencies]
num-bigint = "0.4.2"
