[package]
name = "price-discovery-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = ["Dorin Iancu <dorin.iancu@elrond.com>"]
[dependencies.price-discovery]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.39.2"
