name: CI

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main, feat/* ]

permissions:
  actions: write
  checks: write
  contents: write
  id-token: write
  issues: write
  discussions: write
  pull-requests: write
  statuses: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@v1
    with:
      rust-toolchain: nightly-2022-12-08
      vmtools-version: v1.4.60
      extra-build-args: --ignore-eei-checks
      wasm-tests-args: --features multiversx-sc-scenario/run-go-tests
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
