name: CI

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main, feat/* ]
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  id-token: write
  issues: write
  discussions: write
  pull-requests: write
  statuses: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@12c319e6e6b8c7e452e4a2610f89670d999b54fe
    with:
      rust-toolchain: nightly-2022-12-08
      vmtools-version: v1.4.60
      sc-meta-version: 0.39.4
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
