name: CI

on:
  push:
    branches: [ main, feat/* ]
  pull_request:
    branches: [ main, feat/* ]
  workflow_dispatch:

permissions:
  actions: write
  checks: write
  contents: write
  id-token: write
  issues: write
  discussions: write
  pull-requests: write
  statuses: write

jobs:
  contracts:
    name: Contracts
    uses: multiversx/mx-sc-actions/.github/workflows/contracts.yml@a7cb329409a29fc33a093f16683619dc125baa6a
    with:
      rust-toolchain: nightly-2023-05-26
      vmtools-version: v1.4.60
      sc-meta-version: 0.39.4
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
