name: On pull request, build contracts

on:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@8fe5fca0e7e1d0a56418f1ef559bdf9b12a310c1
    with:
      image_tag: v4.2.0
      package_whole_project_src: true
