name: On pull request, build contracts

on:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@c1e07711ffeda699c5e4ea205adb624d0ab7184c
    with:
      image_tag: v4.2.0
      package_whole_project_src: true
