[package]
name = "farm_mock_v1_4-abi"

version = "0.0.0"
authors = [ "you",]
edition = "2018"
publish = false

[dependencies.farm_mock_v1_4]
path = ".."

[dependencies.elrond-wasm]
version = "=0.23.0"

[dependencies.elrond-wasm-debug]
version = "=0.23.0"
